#https://docs.getdbt.com/reference/dbt_project.yml?version=2.0
name: ecommerce-datahub
version: 1.0.0
require-dbt-version: [ ">=2.0.0-preview.177", "<3.0.0" ]

profile: ecommerce-datahub

seed-paths: [ "seeds" ]
model-paths: [ "models" ]
macro-paths: [ "macros" ]
test-paths: [ "tests" ]
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  ecommerce-datahub:
    +enabled: false # terraform will export seeds file & create external tables

models:
  +persist_docs:
    relation: true
    columns: true

  ecommerce-datahub:
    landing:
      +dataset: "landing"
      +tags:
        - ""

    private:
      +materialized: table
      +dataset: "private"
      +tags:
        - "private"

    public:
      +materialized: table
      +dataset: "public"
      +tags:
        - "public"
