version: 2

sources:
  - name: ecommerce-data-landing_gcs
    database: "{{ env_var('GCP_PROJECT_ID') }}"
    schema: landing
    description: "External tables created by dbt from GCS CSV files."
    tables:
      - name: olist_customers
        description: "External table containing OLIST customer data from GCS CSV file"
        external:
          location: "gs://{{ env_var('GCP_BUCKET_NAME') }}/olist_customers_dataset*.csv"
          options:
            format: csv
            field_delimiter: ","
            skip_leading_rows: 1
      - name: olist_geolocation
        description: "External table containing OLIST geolocation data from GCS CSV file"
        external:
          location: "gs://{{ env_var('GCP_BUCKET_NAME') }}/olist_geolocation_dataset*.csv"
          options:
            format: csv
            field_delimiter: ","
            skip_leading_rows: 1
      - name: olist_order_items
        description: "External table containing OLIST order items data from GCS CSV file"
        external:
          location: "gs://{{ env_var('GCP_BUCKET_NAME') }}/olist_order_items_dataset*.csv"
          options:
            format: csv
            field_delimiter: ","
            skip_leading_rows: 1
      - name: olist_order_payments
        description: "External table containing OLIST order payments data from GCS CSV file"
        external:
          location: "gs://{{ env_var('GCP_BUCKET_NAME') }}/olist_order_payments_dataset*.csv"
          options:
            format: csv
            field_delimiter: ","
            skip_leading_rows: 1
      - name: olist_order_reviews
        description: "External table containing OLIST order reviews data from GCS CSV file"
        external:
          location: "gs://{{ env_var('GCP_BUCKET_NAME') }}/olist_order_reviews_dataset*.csv"
          options:
            format: csv
            field_delimiter: ","
            skip_leading_rows: 1
      - name: olist_orders
        description: "External table containing OLIST orders data from GCS CSV file"
        external:
          location: "gs://{{ env_var('GCP_BUCKET_NAME') }}/olist_orders_dataset*.csv"
          options:
            format: csv
            field_delimiter: ","
            skip_leading_rows: 1
      - name: olist_products
        description: "External table containing OLIST products data from GCS CSV file"
        external:
          location: "gs://{{ env_var('GCP_BUCKET_NAME') }}/olist_products_dataset*.csv"
          options:
            format: csv
            field_delimiter: ","
            skip_leading_rows: 1
      - name: olist_sellers
        description: "External table containing OLIST sellers data from GCS CSV file"
        external:
          location: "gs://{{ env_var('GCP_BUCKET_NAME') }}/olist_sellers_dataset*.csv"
          options:
            format: csv
            field_delimiter: ","
            skip_leading_rows: 1
      - name: product_category_name_translation
        description: "External table containing OLIST product category name translations from GCS CSV file"
        external:
          location: "gs://{{ env_var('GCP_BUCKET_NAME') }}/product_category_name_translation*.csv"
          options:
            format: csv
            field_delimiter: ","
            skip_leading_rows: 1
