version: 2

sources:
  - name: ecommerce-data-landing_gcs
    database: "{{ env_var('GCP_PROJECT_ID') }}"
    schema: landing
    description: "External tables created by dbt from GCS CSV files."
    tables:
      - name: olist_customers
        description: "External table containing OLIST customer data from GCS CSV file"
        external:
          location: "gs://{{ env_var('GCP_BUCKET_NAME') }}/olist_customers_dataset*.csv"
          options:
            format: csv
            field_delimiter: ","
            skip_leading_rows: 1
        columns:
          - name: customer_id
            data_type: STRING
            description: "Unique customer identifier"
          - name: customer_unique_id
            data_type: STRING
            description: "Anonymous customer unique identifier"
          - name: customer_zip_code_prefix
            data_type: STRING
            description: "Customer zip code prefix (first 5 digits)"
          - name: customer_city
            data_type: STRING
            description: "Customer city"
          - name: customer_state
            data_type: STRING
            description: "Customer state (UF - Unidade Federativa)"
